[firebase]
api_key = "AIzaSyBxq8cM66JlJOSJbYbHfXlMHRf3HnyMgoU"
auth_domain = "geg-contractor-payment-system.firebaseapp.com"
database_url = "https://geg-contractor-payment-system-default-rtdb.firebaseio.com"
project_id = "geg-contractor-payment-system"
storage_bucket = "geg-contractor-payment-system.firebasestorage.app"
messaging_sender_id = "459418409739"
app_id = "1:459418409739:web:76e930e1e4e3344573e00e"
measurement_id = ""

[email]
sender = "ammar.muhammed@geg-construction.com"
password = "xhjtfgnordvcpaew"
notify_admin = "admin@geg-construction.com"
