[firebase]
api_key = "AIzaSyBxq8cM66JlJOSJbYbHfXlMHRf3HnyMgoU"
auth_domain = "geg-contractor-payment-system.firebaseapp.com"
project_id = "geg-contractor-payment-system"
storage_bucket = "geg-contractor-payment-system.firebasestorage.app"
messaging_sender_id = "459418409739"
app_id = "1:459418409739:web:76e930e1e4e3344573e00e"
measurement_id = ""
database_url = "https://geg-contractor-payment-system-default-rtdb.firebaseio.com"

[email]
sender = "your_gmail@gmail.com"
password = "your_gmail_app_password"
notify_admin = "admin@geg-construction.com"
