[firebase]
api_key = "your_api_key"
auth_domain = "your_project.firebaseapp.com"
project_id = "your_project"
storage_bucket = "your_project.appspot.com"
messaging_sender_id = "your_sender_id"
app_id = "your_app_id"
measurement_id = "your_measurement_id"
database_url = "https://your_project.firebaseio.com"

[email]
sender = "yourapp@gmail.com"
password = "your_app_password"
notify_admin = "admin@geg-construction.com"
